spring.application.name=springrest

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/myhiber
spring.datasource.username=root
spring.datasource.password=@Vinu1609


#hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true